[package]
name = "go2"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
open = "5.3.2"
ratatui = "0.29.0"
rustic-fuzz = "0.1.0"
